apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: ingress-app
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$2
  namespace: default
spec:
  rules:
  - http:
      paths:
        - path: /api/employees
          backend:
            serviceName: backend
            servicePort: 8080