apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: backend
  name: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - image: backend-img
        name: backend-img
        imagePullPolicy : Never
        ports:
          - containerPort: 8080
        envFrom:
        - configMapRef:
            name: backend-configmap
        env:
        - name: MYSQL_USERNAME
          valueFrom:
            secretKeyRef:
              name: backend-secrets
              key: ROOT_USER_NAME
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: backend-secrets
              key: ROOT_USER_PASSWORD
        
